package sqlconnect

import (
	"bytes"
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"reflect"
	"restapi/internal/models"
	"restapi/pkg/utils"
	"strconv"
	"strings"

	"golang.org/x/crypto/argon2"
)

func GetExecsHandlerFunc() ([]models.Exec, error) {
	query := "SELECT id, first_name, last_name, email, username, password_updated_at, user_created_at, password_reset_code, password_code_expires_at, is_active, role FROM execs WHERE 1=1"
	rows, err := DB.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var execList []models.Exec
	for rows.Next() {
		var exec models.Exec
		err := rows.Scan(
			&exec.ID,
			&exec.FirstName,
			&exec.LastName,
			&exec.Email,
			&exec.Username,
			&exec.PasswordUpdatedAt,
			&exec.UserCreatedAt,
			&exec.PasswordResetCode,
			&exec.PasswordCodeExpires,
			&exec.IsActive,
			&exec.Role,
		)
		if err != nil {
			return nil, err
		}
		execList = append(execList, exec)
	}
	return execList, nil
}

func GetExecHandlerFunc(id int) (models.Exec, error) {
	query := "SELECT id, first_name, last_name, email, username, password_updated_at, user_created_at, password_reset_code, password_code_expires_at, is_active, role FROM execs WHERE id=?"
	var exec models.Exec
	err := DB.QueryRow(query, id).Scan(
		&exec.ID,
		&exec.FirstName,
		&exec.LastName,
		&exec.Email,
		&exec.Username,
		&exec.PasswordUpdatedAt,
		&exec.UserCreatedAt,
		&exec.PasswordResetCode,
		&exec.PasswordCodeExpires,
		&exec.IsActive,
		&exec.Role,
	)
	if err != nil {
		return models.Exec{}, err
	}
	return exec, nil
}

func AddExecHandlerFunc(r *http.Request) ([]models.Exec, error) {
	// 1. Prepare Validation Metadata
	execType := reflect.TypeOf(models.Exec{})
	requiredFields := make(map[string]bool)

	for i := 0; i < execType.NumField(); i++ {
		field := execType.Field(i)
		jsonKey := strings.Split(field.Tag.Get("json"), ",")[0]
		// Exclude ID from required check (usually generated by DB)
		if jsonKey != "id" {
			requiredFields[jsonKey] = true
		}
	}

	// 2. Decode JSON with Strict Validation
	bodyBytes, err := io.ReadAll(r.Body)
	if err != nil {
		return nil, err
	}

	var newExecs []models.Exec
	decode := func(data []byte, target interface{}) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields() // Prevent EXTRA fields
		return decoder.Decode(target)
	}

	// Try to decode as array
	if err := decode(bodyBytes, &newExecs); err != nil {
		// If array fails, try decoding as a single object
		var singleExec models.Exec
		if errSingle := decode(bodyBytes, &singleExec); errSingle != nil {
			return nil, fmt.Errorf("client: Invalid Request Body (Extra fields or bad format): %v", errSingle)
		}
		newExecs = []models.Exec{singleExec}
	}

	// 3. Validate Required Fields (Missing/Empty Check)
	for _, exec := range newExecs {
		val := reflect.ValueOf(exec)
		for i := 0; i < execType.NumField(); i++ {
			fieldVal := val.Field(i)
			jsonKey := strings.Split(execType.Field(i).Tag.Get("json"), ",")[0]

			if requiredFields[jsonKey] && fieldVal.Kind() == reflect.String && fieldVal.String() == "" {
				return nil, fmt.Errorf("client: Required field '%s' is missing or empty", jsonKey)
			}
		}
	}

	// 4. Database Persistence
	stmt, err := DB.Prepare(utils.GenerateInsertQuery("execs", models.Exec{}))
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	addedExecs := make([]models.Exec, len(newExecs))

	for i, newExec := range newExecs {
		if newExec.Password == "" {
			return nil, utils.ErrorHandler(errors.New("Please Enter password"), "please Enter your password")
		}
		salt := make([]byte, 16)
		_, err := rand.Read(salt)
		if err != nil {
			return nil, utils.ErrorHandler(errors.New("Failed to generate salt"), "error adding data")
		}

		hash := argon2.IDKey([]byte(newExec.Password), salt, 1, 64*1024, 2, 32)
		saltBase64 := base64.StdEncoding.EncodeToString(salt)
		hashBase64 := base64.StdEncoding.EncodeToString(hash)
		encodedHash := fmt.Sprintf("%s.%s", saltBase64, hashBase64)
		newExec.Password = encodedHash

		values := utils.GetStructValues(newExec)
		res, err := stmt.Exec(values...)
		if err != nil {
			return nil, err
		}
		lastId, err := res.LastInsertId()
		if err != nil {
			return nil, err
		}
		newExec.ID = int(lastId)
		newExec.Password = "" // NEVER SEND THE PASSWORD
		addedExecs[i] = newExec
	}
	return addedExecs, nil
}

func DeleteExecsHandlerFunc(r *http.Request) error {
	var deletes []map[string]interface{}
	if err := json.NewDecoder(r.Body).Decode(&deletes); err != nil {
		return err
	}
	var deleteIdList []interface{}

	for _, v := range deletes {
		if id, ok := v["id"].(float64); ok {
			deleteIdList = append(deleteIdList, int(id))
		} else if id, ok := v["id"].(int); ok {
			deleteIdList = append(deleteIdList, id)
		} else if idStr, ok := v["id"].(string); ok {
			if id, err := strconv.Atoi(idStr); err == nil {
				deleteIdList = append(deleteIdList, id)
			}
		}
	}

	if len(deleteIdList) == 0 {
		return fmt.Errorf("no valid IDs provided")
	}
	placeholders := make([]string, len(deleteIdList))
	for i := range placeholders {
		placeholders[i] = "?"
	}
	query := fmt.Sprintf("DELETE FROM execs WHERE id IN (%s)", strings.Join(placeholders, ","))
	// 3. Use DB.Exec with the list of IDs
	_, err := DB.Exec(query, deleteIdList...)
	if err != nil {
		return err
	}
	return nil
}

func DeleteExecHandlerFunc(id int) error {
	res, err := DB.Exec("DELETE FROM execs WHERE id = ?", id)
	if err != nil {
		return err
	}

	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return err
	}

	if rowsAffected == 0 {
		return fmt.Errorf("client: Exec not found")
	}
	return nil
}

func PatchExecHandlerFunc(id int, r *http.Request) (models.Exec, error) {
	var existingExec models.Exec

	err := DB.QueryRow("SELECT id, first_name, last_name, email, username, is_active, role FROM execs WHERE id = ?", id).Scan(
		&existingExec.ID,
		&existingExec.FirstName,
		&existingExec.LastName,
		&existingExec.Email,
		&existingExec.Username,
		&existingExec.IsActive,
		&existingExec.Role)

	if err != nil {
		if err == sql.ErrNoRows {
			return models.Exec{}, err
		}
		return models.Exec{}, utils.ErrorHandler(err, "Error retrieving exec data from DB")
	}

	var updates map[string]interface{}
	err = json.NewDecoder(r.Body).Decode(&updates)
	if err != nil {
		return models.Exec{}, utils.ErrorHandler(err, "client: Invalid Request Body")
	}

	val := reflect.ValueOf(&existingExec).Elem()
	typeOf := val.Type()
	fmt.Println("Type of :", typeOf)

	for k, v := range updates {
		for i := 0; i < val.NumField(); i++ {
			field := typeOf.Field(i)
			tag := field.Tag.Get("json")
			jsonKey := strings.Split(tag, ",")[0]

			if jsonKey == k {
				fieldVal := val.Field(i)
				if fieldVal.CanSet() {
					currVal := reflect.ValueOf(v)
					if currVal.Type().ConvertibleTo(fieldVal.Type()) {
						fieldVal.Set(currVal.Convert(fieldVal.Type()))
					} else {
						return models.Exec{}, fmt.Errorf("client: type mismatch for field %s", k)
					}
				}
			}
		}
	}

	_, err = DB.Exec("UPDATE execs SET first_name = ?, last_name = ?, email = ?, username = ?, is_active = ?, role = ? WHERE id = ?",
		existingExec.FirstName, existingExec.LastName, existingExec.Email, existingExec.Username, existingExec.IsActive, existingExec.Role, id)

	if err != nil {
		return models.Exec{}, utils.ErrorHandler(err, "Error executing update query")
	}

	existingExec.ID = id
	return existingExec, nil
}

func PatchExecsHandlerFunc(r *http.Request) error {
	var updates []map[string]interface{}

	err := json.NewDecoder(r.Body).Decode(&updates)
	if err != nil {
		return fmt.Errorf("client: invalid JSON body: %v", err)
	}

	tx, err := DB.Begin()
	if err != nil {
		return err
	}
	for _, update := range updates {
		// Robust ID extraction: handles Numbers (float64), Integers, and Strings from JSON
		var id int
		var idValid bool
		if v, ok := update["id"].(float64); ok {
			id = int(v)
			idValid = true
		} else if v, ok := update["id"].(int); ok {
			id = v
			idValid = true
		} else if v, ok := update["id"].(string); ok {
			if parsedId, err := strconv.Atoi(v); err == nil {
				id = parsedId
				idValid = true
			}
		}

		if !idValid {
			tx.Rollback()
			return fmt.Errorf("client: Invalid or missing exec id in update")
		}

		var execFromDb models.Exec
		err = tx.QueryRow("SELECT id, first_name, last_name, email, username, is_active, role FROM execs WHERE id = ?", id).Scan(
			&execFromDb.ID, &execFromDb.FirstName, &execFromDb.LastName, &execFromDb.Email, &execFromDb.Username, &execFromDb.IsActive, &execFromDb.Role,
		)
		if err != nil {
			tx.Rollback()
			if err == sql.ErrNoRows {
				return err
			}
			return err
		}

		val := reflect.ValueOf(&execFromDb).Elem()
		typeOf := val.Type()

		for k, v := range update {
			if k == "id" {
				continue
			}
			for i := 0; i < val.NumField(); i++ {
				field := typeOf.Field(i)
				tag := field.Tag.Get("json")
				jsonKey := strings.Split(tag, ",")[0]

				if jsonKey == k {
					fieldVal := val.Field(i)
					if fieldVal.CanSet() {
						currVal := reflect.ValueOf(v)
						if currVal.Type().ConvertibleTo(fieldVal.Type()) {
							fieldVal.Set(currVal.Convert(fieldVal.Type()))
						} else {
							tx.Rollback()
							return fmt.Errorf("client: Type mismatch for field %s", k)
						}
					}
				}
			}
		}
		_, err = tx.Exec("UPDATE execs SET first_name = ?, last_name = ?, email = ?, username = ?, is_active = ?, role = ? WHERE id = ?",
			execFromDb.FirstName, execFromDb.LastName, execFromDb.Email, execFromDb.Username, execFromDb.IsActive, execFromDb.Role, execFromDb.ID)
		if err != nil {
			tx.Rollback()
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	return nil
}

func UpdateExecFunc(r *http.Request, id int) (models.Exec, error) {
	var updatedExecs models.Exec
	err := json.NewDecoder(r.Body).Decode(&updatedExecs)
	if err != nil {
		return models.Exec{}, utils.ErrorHandler(err, "client: Invalid Request Body")
	}

	var existingExec models.Exec
	err = DB.QueryRow("SELECT id, first_name, last_name, email, username, is_active, role FROM execs WHERE id = ?", id).Scan(
		&existingExec.ID,
		&existingExec.FirstName,
		&existingExec.LastName,
		&existingExec.Email,
		&existingExec.Username,
		&existingExec.IsActive,
		&existingExec.Role)

	if err != nil {
		if err == sql.ErrNoRows {
			return models.Exec{}, err
		}
		return models.Exec{}, utils.ErrorHandler(err, "Error retrieving exec data from DB")
	}
	_, err = DB.Exec("UPDATE execs SET first_name = ?, last_name = ?, email = ?, username = ?, is_active = ?, role = ? WHERE id = ?",
		updatedExecs.FirstName, updatedExecs.LastName, updatedExecs.Email, updatedExecs.Username, updatedExecs.IsActive, updatedExecs.Role, id)

	if err != nil {
		return models.Exec{}, utils.ErrorHandler(err, "Error executing update query")
	}

	updatedExecs.ID = id
	updatedExecs.Password = "" // NEVER SEND THE PASSWORD
	return updatedExecs, nil
}
