package sqlconnect

import (
	"bytes"
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"reflect"
	"restapi/internal/models"
	"restapi/pkg/utils"
	"strconv"
	"strings"
)

func GetStudentHandlerFunc(id int) (models.Student, error) {
	query := "Select id, first_name, last_name, email, class from students where id=? "

	var student models.Student
	err := DB.QueryRow(query, id).Scan(&student.ID, &student.FirstName, &student.LastName, &student.Email, &student.Class)

	if err == sql.ErrNoRows {
		return models.Student{}, err
	} else if err != nil {
		return models.Student{}, utils.ErrorHandler(err, "Error retrieving student")
	}
	return student, nil
}

func GetStudentsHandlerFunc(r *http.Request) ([]models.Student, error) {
	var args []interface{}

	query := "Select id, first_name, last_name, email, class from students where 1=1"
	query, args = utils.AddFilters(r, query, args)

	rows, err := DB.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	studentList := make([]models.Student, 0)

	for rows.Next() {
		var student models.Student
		err := rows.Scan(&student.ID, &student.FirstName, &student.LastName, &student.Email, &student.Class)
		if err != nil {
			return studentList, err
		}
		studentList = append(studentList, student)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return studentList, nil
}

func AddStudentHandlerFunc(r *http.Request) ([]models.Student, error) {
	// 1. Prepare Validation Metadata
	studentType := reflect.TypeOf(models.Student{})
	requiredFields := make(map[string]bool)

	for i := 0; i < studentType.NumField(); i++ {
		field := studentType.Field(i)
		jsonKey := strings.Split(field.Tag.Get("json"), ",")[0]
		// Exclude ID from required check (usually generated by DB)
		if jsonKey != "id" {
			requiredFields[jsonKey] = true
		}
	}

	// 2. Decode JSON with Strict Validation
	bodyBytes, err := io.ReadAll(r.Body)
	if err != nil {
		return nil, err
	}

	var newStudents []models.Student
	decode := func(data []byte, target interface{}) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields() // Prevent EXTRA fields
		return decoder.Decode(target)
	}

	// Try to decode as array
	if err := decode(bodyBytes, &newStudents); err != nil {
		// If array fails, try decoding as a single object
		var singleStudent models.Student
		if errSingle := decode(bodyBytes, &singleStudent); errSingle != nil {
			return nil, fmt.Errorf("client: Invalid Request Body (Extra fields or bad format): %v", errSingle)
		}
		newStudents = []models.Student{singleStudent}
	}

	// 3. Validate Required Fields (Missing/Empty Check)
	for _, student := range newStudents {
		val := reflect.ValueOf(student)
		for i := 0; i < studentType.NumField(); i++ {
			fieldVal := val.Field(i)
			jsonKey := strings.Split(studentType.Field(i).Tag.Get("json"), ",")[0]

			if requiredFields[jsonKey] && fieldVal.Kind() == reflect.String && fieldVal.String() == "" {
				return nil, fmt.Errorf("client: Required field '%s' is missing or empty", jsonKey)
			}
		}
	}

	// 4. Database Persistence
	stmt, err := DB.Prepare(utils.GenerateInsertQuery("students", models.Student{}))
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	addedStudents := make([]models.Student, len(newStudents))

	for i, newStudent := range newStudents {
		values := utils.GetStructValues(newStudent)
		res, err := stmt.Exec(values...)
		if err != nil {
			return nil, err
		}
		lastId, err := res.LastInsertId()
		if err != nil {
			return nil, err
		}
		newStudent.ID = int(lastId)
		addedStudents[i] = newStudent
	}
	return addedStudents, nil
}

func DeleteStudentsHandlerFunc(r *http.Request) error {
	var deletes []map[string]interface{}
	if err := json.NewDecoder(r.Body).Decode(&deletes); err != nil {
		return err
	}
	var deleteIdList []interface{}

	for _, v := range deletes {
		if id, ok := v["id"].(float64); ok {
			deleteIdList = append(deleteIdList, int(id))
		} else if id, ok := v["id"].(int); ok {
			deleteIdList = append(deleteIdList, id)
		} else if idStr, ok := v["id"].(string); ok {
			if id, err := strconv.Atoi(idStr); err == nil {
				deleteIdList = append(deleteIdList, id)
			}
		}
	}

	if len(deleteIdList) == 0 {
		return fmt.Errorf("no valid IDs provided")
	}
	placeholders := make([]string, len(deleteIdList))
	for i := range placeholders {
		placeholders[i] = "?"
	}
	query := fmt.Sprintf("DELETE FROM students WHERE id IN (%s)", strings.Join(placeholders, ","))
	// 3. Use DB.Exec with the list of IDs
	_, err := DB.Exec(query, deleteIdList...)
	if err != nil {
		return err
	}
	return nil
}

func DeleteStudentHandlerFunc(id int) error {
	res, err := DB.Exec("DELETE FROM students WHERE id = ?", id)
	if err != nil {
		return err
	}

	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return err
	}

	if rowsAffected == 0 {
		return fmt.Errorf("client: Student not found")
	}
	return nil
}

func PatchStudentHandlerFunc(id int, r *http.Request) (models.Student, error) {
	var existingStudent models.Student

	err := DB.QueryRow("Select id, first_name, last_name, email, class from students where id = ?", id).Scan(
		&existingStudent.ID,
		&existingStudent.FirstName,
		&existingStudent.LastName,
		&existingStudent.Email,
		&existingStudent.Class)

	if err != nil {
		if err == sql.ErrNoRows {
			return models.Student{}, err
		}
		return models.Student{}, utils.ErrorHandler(err, "Error retrieving student data from DB")
	}

	var updates map[string]interface{}
	err = json.NewDecoder(r.Body).Decode(&updates)
	if err != nil {
		return models.Student{}, utils.ErrorHandler(err, "client: Invalid Request Body")
	}

	val := reflect.ValueOf(&existingStudent).Elem()
	typeOf := val.Type()
	fmt.Println("Type of :", typeOf)

	for k, v := range updates {
		for i := 0; i < val.NumField(); i++ {
			filed := typeOf.Field(i)
			tag := filed.Tag.Get("json")
			jsonKey := strings.Split(tag, ",")[0]

			if jsonKey == k {
				fieldVal := val.Field(i)
				if fieldVal.CanSet() {
					currVal := reflect.ValueOf(v)
					// Add this check like you did in the other function!
					if currVal.Type().ConvertibleTo(fieldVal.Type()) {
						fieldVal.Set(currVal.Convert(fieldVal.Type()))
					} else {
						return models.Student{}, fmt.Errorf("client: type mismatch for field %s", k)
					}
				}
			}

		}
	}

	_, err = DB.Exec("update students set first_name = ? , last_name = ? , email = ? , class = ? where id = ? ",
		existingStudent.FirstName, existingStudent.LastName, existingStudent.Email, existingStudent.Class, id)

	if err != nil {
		return models.Student{}, utils.ErrorHandler(err, "Error executing update query")
	}

	existingStudent.ID = id // Ensure ID is in the response
	fmt.Printf("Successfully updated student with ID %d\n", id)
	return existingStudent, nil
}

func PatchStudentsHandlerFunc(r *http.Request) error {
	var updates []map[string]interface{}

	err := json.NewDecoder(r.Body).Decode(&updates)
	if err != nil {
		return fmt.Errorf("client: invalid JSON body: %v", err)
	}

	tx, err := DB.Begin()
	if err != nil {
		return err
	}
	for _, update := range updates {
		// Robust ID extraction: handles Numbers (float64), Integers, and Strings from JSON
		var id int
		var idValid bool
		if v, ok := update["id"].(float64); ok {
			id = int(v)
			idValid = true
		} else if v, ok := update["id"].(int); ok {
			id = v
			idValid = true
		} else if v, ok := update["id"].(string); ok {
			if parsedId, err := strconv.Atoi(v); err == nil {
				id = parsedId
				idValid = true
			}
		}

		if !idValid {
			tx.Rollback()
			return fmt.Errorf("client: Invalid or missing student id in update")
		}

		var studentFromDb models.Student
		// Use tx instead of DB to keep it in the transaction
		err = tx.QueryRow("Select id, first_name, last_name, email, class from students where id = ?", id).Scan(
			&studentFromDb.ID, &studentFromDb.FirstName, &studentFromDb.LastName, &studentFromDb.Email, &studentFromDb.Class,
		)
		if err != nil {
			tx.Rollback()
			if err == sql.ErrNoRows {
				return err
			}
			return err
		}

		val := reflect.ValueOf(&studentFromDb).Elem()
		typeOf := val.Type()

		for k, v := range update {
			if k == "id" {
				continue
			}
			for i := 0; i < val.NumField(); i++ {
				filed := typeOf.Field(i)
				tag := filed.Tag.Get("json")
				jsonKey := strings.Split(tag, ",")[0]

				if jsonKey == k {
					fieldVal := val.Field(i)
					if fieldVal.CanSet() {
						currVal := reflect.ValueOf(v)
						// Fix: check if the VALUE (currVal) is convertible to the FIELD
						if currVal.Type().ConvertibleTo(fieldVal.Type()) {
							fieldVal.Set(currVal.Convert(fieldVal.Type()))
						} else {
							tx.Rollback()
							return fmt.Errorf("client: Type mismatch for field %s", k)
						}
					}
				}

			}
		}
		_, err = tx.Exec("Update students set first_name = ?, last_name = ?, email = ?, class = ? where id = ?",
			studentFromDb.FirstName, studentFromDb.LastName, studentFromDb.Email, studentFromDb.Class, studentFromDb.ID)
		if err != nil {
			tx.Rollback()
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	return nil
}

func UpdateStudentFunc(r *http.Request, id int) (models.Student, error) {
	var updatedStudents models.Student
	err := json.NewDecoder(r.Body).Decode(&updatedStudents)
	if err != nil {
		return models.Student{}, utils.ErrorHandler(err, "client: Invalid Request Body")
	}

	var existingStudent models.Student

	err = DB.QueryRow("Select id, first_name, last_name, email,  class from students where id = ?", id).Scan(
		&existingStudent.ID,
		&existingStudent.FirstName,
		&existingStudent.LastName,
		&existingStudent.Email,
		&existingStudent.Class)

	if err != nil {
		if err == sql.ErrNoRows {
			return models.Student{}, err
		}
		return models.Student{}, utils.ErrorHandler(err, "Error retrieving student data from DB")
	}
	_, err = DB.Exec("update students set first_name = ? , last_name = ? , email = ? , class = ?  where id = ? ",
		updatedStudents.FirstName, updatedStudents.LastName, updatedStudents.Email, updatedStudents.Class, id)

	if err != nil {
		return models.Student{}, utils.ErrorHandler(err, "Error executing update query")
	}

	updatedStudents.ID = id // Ensure ID is in the response
	fmt.Printf("Successfully updated student with ID %d\n", id)
	return updatedStudents, nil
}
