package sqlconnect

import (
	"bytes"
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"reflect"
	"restapi/internal/models"
	"restapi/pkg/utils"
	"strconv"
	"strings"
)

func GetTeacherHandlerFunc(id int) (models.Teacher, error) {
	query := "Select id, first_name, last_name, email, class, subject from teachers where id=? "

	var teacher models.Teacher
	err := DB.QueryRow(query, id).Scan(&teacher.ID, &teacher.FirstName, &teacher.LastName, &teacher.Email, &teacher.Class, &teacher.Subject)

	if err == sql.ErrNoRows {
		return models.Teacher{}, err
	} else if err != nil {
		return models.Teacher{}, utils.ErrorHandler(err, "Error retrieving teacher")
	}
	return teacher, nil
}

func GetTeachersHandlerFunc(r *http.Request) ([]models.Teacher, error) {
	var args []interface{}

	query := "Select id, first_name, last_name, email, class, subject from teachers where 1=1"
	query, args = utils.AddFilters(r, query, args)

	rows, err := DB.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	teacherList := make([]models.Teacher, 0)

	for rows.Next() {
		var teacher models.Teacher
		err := rows.Scan(&teacher.ID, &teacher.FirstName, &teacher.LastName, &teacher.Email, &teacher.Class, &teacher.Subject)
		if err != nil {
			return teacherList, err
		}
		teacherList = append(teacherList, teacher)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return teacherList, nil
}

func GetStudentCountOfTeacherFunc(id int) (int, error) {
	query := "Select count(*) from students where class = (select class from teachers where id = ?)"
	var count int
	err := DB.QueryRow(query, id).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func GetStudentsOfTeachersFunc(id int) ([]models.Student, error) {
	query := "Select id, first_name, last_name, email, class from students where class = (select class from teachers where id = ?)"
	rows, err := DB.Query(query, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	studentList := []models.Student{}
	for rows.Next() {
		var student models.Student
		err := rows.Scan(&student.ID, &student.FirstName, &student.LastName, &student.Email, &student.Class)
		if err != nil {
			return nil, err
		}
		studentList = append(studentList, student)
	}
	return studentList, nil
}

func AddTeacherHandlerFunc(r *http.Request) ([]models.Teacher, error) {
	// 1. Prepare Validation Metadata
	teacherType := reflect.TypeOf(models.Teacher{})
	requiredFields := make(map[string]bool)

	for i := 0; i < teacherType.NumField(); i++ {
		field := teacherType.Field(i)
		jsonKey := strings.Split(field.Tag.Get("json"), ",")[0]
		// Exclude ID from required check (usually generated by DB)
		if jsonKey != "id" {
			requiredFields[jsonKey] = true
		}
	}

	// 2. Decode JSON with Strict Validation
	bodyBytes, err := io.ReadAll(r.Body)
	if err != nil {
		return nil, err
	}

	var newTeachers []models.Teacher
	decode := func(data []byte, target interface{}) error {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields() // Prevent EXTRA fields
		return decoder.Decode(target)
	}

	// Try to decode as array
	if err := decode(bodyBytes, &newTeachers); err != nil {
		// If array fails, try decoding as a single object
		var singleTeacher models.Teacher
		if errSingle := decode(bodyBytes, &singleTeacher); errSingle != nil {
			return nil, fmt.Errorf("client: Invalid Request Body (Extra fields or bad format): %v", errSingle)
		}
		newTeachers = []models.Teacher{singleTeacher}
	}

	// 3. Validate Required Fields (Missing/Empty Check)
	for _, teacher := range newTeachers {
		val := reflect.ValueOf(teacher)
		for i := 0; i < teacherType.NumField(); i++ {
			fieldVal := val.Field(i)
			jsonKey := strings.Split(teacherType.Field(i).Tag.Get("json"), ",")[0]

			if requiredFields[jsonKey] && fieldVal.Kind() == reflect.String && fieldVal.String() == "" {
				return nil, fmt.Errorf("client: Required field '%s' is missing or empty", jsonKey)
			}
		}
	}

	// 4. Database Persistence
	stmt, err := DB.Prepare(utils.GenerateInsertQuery("teachers", models.Teacher{}))
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	addedTeachers := make([]models.Teacher, len(newTeachers))

	for i, newTeacher := range newTeachers {
		values := utils.GetStructValues(newTeacher)
		res, err := stmt.Exec(values...)
		if err != nil {
			return nil, err
		}
		lastId, err := res.LastInsertId()
		if err != nil {
			return nil, err
		}
		newTeacher.ID = int(lastId)
		addedTeachers[i] = newTeacher
	}
	return addedTeachers, nil
}

func generateInsertQuery(model interface{}) string {
	modelType := reflect.TypeOf(model)
	var columns, placeholders string

	for i := 0; i < modelType.NumField(); i++ {
		dbTag := strings.Split(modelType.Field(i).Tag.Get("db"), ",")[0]
		fmt.Println(dbTag)
		if dbTag != "" && dbTag != "id" {
			if columns != "" {
				columns += " ,"
				placeholders += " ,"
			}
			columns += dbTag
			placeholders += "?"
		}
	}
	return fmt.Sprintf("Insert into teachers (%s) values (%s)", columns, placeholders)
}

func DeleteTeachersHandlerFunc(r *http.Request) error {
	var deletes []map[string]interface{}
	if err := json.NewDecoder(r.Body).Decode(&deletes); err != nil {
		return err
	}
	var deleteIdList []interface{}

	for _, v := range deletes {
		if id, ok := v["id"].(float64); ok {
			deleteIdList = append(deleteIdList, int(id))
		} else if id, ok := v["id"].(int); ok {
			deleteIdList = append(deleteIdList, id)
		} else if idStr, ok := v["id"].(string); ok {
			if id, err := strconv.Atoi(idStr); err == nil {
				deleteIdList = append(deleteIdList, id)
			}
		}
	}

	if len(deleteIdList) == 0 {
		return fmt.Errorf("no valid IDs provided")
	}
	placeholders := make([]string, len(deleteIdList))
	for i := range placeholders {
		placeholders[i] = "?"
	}
	query := fmt.Sprintf("DELETE FROM teachers WHERE id IN (%s)", strings.Join(placeholders, ","))
	// 3. Use DB.Exec with the list of IDs
	_, err := DB.Exec(query, deleteIdList...)
	if err != nil {
		return err
	}
	return nil
}

func DeleteTeacherHandlerFunc(id int) error {
	res, err := DB.Exec("DELETE FROM teachers WHERE id = ?", id)
	if err != nil {
		return err
	}

	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return err
	}

	if rowsAffected == 0 {
		return fmt.Errorf("client: Teacher not found")
	}
	return nil
}

func PatchTeacherHandlerFunc(id int, r *http.Request) (models.Teacher, error) {
	var existingTeacher models.Teacher

	err := DB.QueryRow("Select id, first_name, last_name, email, subject, class from teachers where id = ?", id).Scan(
		&existingTeacher.ID,
		&existingTeacher.FirstName,
		&existingTeacher.LastName,
		&existingTeacher.Email,
		&existingTeacher.Subject,
		&existingTeacher.Class)

	if err != nil {
		if err == sql.ErrNoRows {
			return models.Teacher{}, err
		}
		return models.Teacher{}, utils.ErrorHandler(err, "Error retrieving teacher data from DB")
	}

	var updates map[string]interface{}
	err = json.NewDecoder(r.Body).Decode(&updates)
	if err != nil {
		return models.Teacher{}, utils.ErrorHandler(err, "client: Invalid Request Body")
	}

	val := reflect.ValueOf(&existingTeacher).Elem()
	typeOf := val.Type()
	fmt.Println("Type of :", typeOf)

	for k, v := range updates {
		for i := 0; i < val.NumField(); i++ {
			filed := typeOf.Field(i)
			tag := filed.Tag.Get("json")
			jsonKey := strings.Split(tag, ",")[0]

			if jsonKey == k {
				fieldVal := val.Field(i)
				if fieldVal.CanSet() {
					currVal := reflect.ValueOf(v)
					// Add this check like you did in the other function!
					if currVal.Type().ConvertibleTo(fieldVal.Type()) {
						fieldVal.Set(currVal.Convert(fieldVal.Type()))
					} else {
						return models.Teacher{}, fmt.Errorf("client: type mismatch for field %s", k)
					}
				}
			}

		}
	}

	_, err = DB.Exec("update teachers set first_name = ? , last_name = ? , email = ? , class = ? , subject = ? where id = ? ",
		existingTeacher.FirstName, existingTeacher.LastName, existingTeacher.Email, existingTeacher.Class, existingTeacher.Subject, id)

	if err != nil {
		return models.Teacher{}, utils.ErrorHandler(err, "Error executing update query")
	}

	existingTeacher.ID = id // Ensure ID is in the response
	fmt.Printf("Successfully updated teacher with ID %d\n", id)
	return existingTeacher, nil
}

func PatchTeachersHandlerFunc(r *http.Request) error {
	var updates []map[string]interface{}

	err := json.NewDecoder(r.Body).Decode(&updates)
	if err != nil {
		return fmt.Errorf("client: invalid JSON body: %v", err)
	}

	tx, err := DB.Begin()
	if err != nil {
		return err
	}
	for _, update := range updates {
		// Robust ID extraction: handles Numbers (float64), Integers, and Strings from JSON
		var id int
		var idValid bool
		if v, ok := update["id"].(float64); ok {
			id = int(v)
			idValid = true
		} else if v, ok := update["id"].(int); ok {
			id = v
			idValid = true
		} else if v, ok := update["id"].(string); ok {
			if parsedId, err := strconv.Atoi(v); err == nil {
				id = parsedId
				idValid = true
			}
		}

		if !idValid {
			tx.Rollback()
			return fmt.Errorf("client: Invalid or missing teacher id in update")
		}

		var teacherFromDb models.Teacher
		// Use tx instead of DB to keep it in the transaction
		err = tx.QueryRow("Select id, first_name, last_name, email, class, subject from teachers where id = ?", id).Scan(
			&teacherFromDb.ID, &teacherFromDb.FirstName, &teacherFromDb.LastName, &teacherFromDb.Email, &teacherFromDb.Class,
			&teacherFromDb.Subject,
		)
		if err != nil {
			tx.Rollback()
			if err == sql.ErrNoRows {
				return err
			}
			return err
		}

		val := reflect.ValueOf(&teacherFromDb).Elem()
		typeOf := val.Type()

		for k, v := range update {
			if k == "id" {
				continue
			}
			for i := 0; i < val.NumField(); i++ {
				filed := typeOf.Field(i)
				tag := filed.Tag.Get("json")
				jsonKey := strings.Split(tag, ",")[0]

				if jsonKey == k {
					fieldVal := val.Field(i)
					if fieldVal.CanSet() {
						currVal := reflect.ValueOf(v)
						// Fix: check if the VALUE (currVal) is convertible to the FIELD
						if currVal.Type().ConvertibleTo(fieldVal.Type()) {
							fieldVal.Set(currVal.Convert(fieldVal.Type()))
						} else {
							tx.Rollback()
							return fmt.Errorf("client: Type mismatch for field %s", k)
						}
					}
				}

			}
		}
		_, err = tx.Exec("Update teachers set first_name = ?, last_name = ?, email = ?, class = ?, subject = ? where id = ?",
			teacherFromDb.FirstName, teacherFromDb.LastName, teacherFromDb.Email, teacherFromDb.Class, teacherFromDb.Subject, teacherFromDb.ID)
		if err != nil {
			tx.Rollback()
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	return nil
}

func UpdateTeacherFunc(r *http.Request, id int) (models.Teacher, error) {
	var updatedTeachers models.Teacher
	err := json.NewDecoder(r.Body).Decode(&updatedTeachers)
	if err != nil {
		return models.Teacher{}, utils.ErrorHandler(err, "client: Invalid Request Body")
	}

	var existingTeacher models.Teacher

	err = DB.QueryRow("Select id, first_name, last_name, email, subject, class from teachers where id = ?", id).Scan(
		&existingTeacher.ID,
		&existingTeacher.FirstName,
		&existingTeacher.LastName,
		&existingTeacher.Email,
		&existingTeacher.Subject,
		&existingTeacher.Class)

	if err != nil {
		if err == sql.ErrNoRows {
			return models.Teacher{}, err
		}
		return models.Teacher{}, utils.ErrorHandler(err, "Error retrieving teacher data from DB")
	}
	_, err = DB.Exec("update teachers set first_name = ? , last_name = ? , email = ? , class = ? , subject = ? where id = ? ",
		updatedTeachers.FirstName, updatedTeachers.LastName, updatedTeachers.Email, updatedTeachers.Class, updatedTeachers.Subject, id)

	if err != nil {
		return models.Teacher{}, utils.ErrorHandler(err, "Error executing update query")
	}

	updatedTeachers.ID = id // Ensure ID is in the response
	fmt.Printf("Successfully updated teacher with ID %d\n", id)
	return updatedTeachers, nil
}
